GET http://localhost:4000/posts

###

POST http://localhost:4000/posts
Content-Type: application/json

{
    "title": "Mongo DB 1",
    "text": "Mongo DB is best database ever 1"
}

###

GET http://localhost:4000/posts/637ff1a42fbec8accd35dc34



###


DELETE http://localhost:4000/posts/637ff22180cc997b6d58ae85